<?php

/** @var AHT\CustomCheckout\Block\Adminhtml\Order\Delivery $block */
$order = $block->getOrder();

?>
<div class="admin__page-section-item order-payment-method">
    <div class="admin__page-section-item-title">
        <span class="title">Delivery Information</span>
        <span><?= /* @noEscape */ $block->getEditLink(); ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <p><span><label>Date : </label></span><?= $block->escapeHtml($order->getDeliveryDate()) ?></p>
        <p><span><label>Comment : </label></span><?= $block->escapeHtml($order->getDeliveryComment()) ?></p>
    </div>